
const STATUS_CODE_OK = 200;
const STATUS_CODE_NOT_FOUND = 404;
const STATUS_CODE_BAD_REQUEST = 400;
const STATUS_CODE_UNAUTHORIZED = 401;
const STATUS_CODE_SERVER_ERROR = 500;
const STATUS_CODE_ACCESS_DENIED = 403;
const users = '/api/v1/users';

module.exports = {
  STATUS_CODE_OK,
  STATUS_CODE_NOT_FOUND,
  STATUS_CODE_BAD_REQUEST,
  STATUS_CODE_SERVER_ERROR,
  STATUS_CODE_UNAUTHORIZED,
  STATUS_CODE_ACCESS_DENIED,
  users,
};
